### ISSUE TITLE
datasets 

### ISSUE THREAD

**Issue by gschwend** [linea-it/docs#47]
Sugestões: 
* a página de datasets está incompleta demais para ficar no ar como está, sugiro editar em outro branch e só fazer o merge quando tiver algum conteúdo, ou pelo menos um disclaimer de página em construção.  
*  Título no menu em português para ficar consistente com o resto da página (data --> dados)

**Comment by carlosadean** [comment]
Foi adicionado um aviso de 'warning' nas páginas citadas.
